const { jsPDF } = window.jspdf;

const searchInput = document.getElementById("searchInput");
const searchBtn = document.getElementById("searchBtn");
const results = document.getElementById("results");

searchBtn.addEventListener("click", searchMeals);
searchInput.addEventListener("keydown", e => { if (e.key === "Enter") searchMeals(); });

async function searchMeals() {
  const query = searchInput.value.trim();
  if (!query) return alert("Please enter a meal name!");

  results.innerHTML = "<p>Loading recipes...</p>";
  try {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=${encodeURIComponent(query)}`);
    const data = await res.json();
    if (!data.meals) return results.innerHTML = "<p>No recipes found 😢</p>";

    results.innerHTML = data.meals.map(meal => recipeCardHtml(meal)).join("");
    attachDownloadHandlers();
  } catch {
    results.innerHTML = "<p>Error loading recipes. Try again later.</p>";
  }
}

function recipeCardHtml(meal) {
  const ingredients = getIngredients(meal);
  return `
    <div class="recipe" data-mealid="${meal.idMeal}">
      <img src="${meal.strMealThumb}" alt="${meal.strMeal}">
      <h2>${meal.strMeal}</h2>
      <h4>Ingredients:</h4>
      <ul>${ingredients.map(i => `<li>${i}</li>`).join("")}</ul>
      <h4>Instructions:</h4>
      <p>${meal.strInstructions.slice(0, 400)}${meal.strInstructions.length>400?'...':''}</p>
      <div style="margin-top:8px;display:flex;gap:8px;flex-wrap:wrap;">
        <a href="${meal.strSource || meal.strYoutube || '#'}" target="_blank" class="link">Full Recipe →</a>
        <button class="downloadPdfBtn" data-id="${meal.idMeal}">Download PDF</button>
      </div>
    </div>`;
}

function getIngredients(meal) {
  const list = [];
  for (let i = 1; i <= 20; i++) {
    const item = meal[`strIngredient${i}`]?.trim();
    const measure = meal[`strMeasure${i}`]?.trim();
    if (item) list.push(measure ? `${item} — ${measure}` : item);
  }
  return list;
}

function attachDownloadHandlers() {
  document.querySelectorAll(".downloadPdfBtn").forEach(btn =>
    btn.addEventListener("click", async e => {
      const id = e.currentTarget.dataset.id;
      const meal = await fetchMealById(id);
      if (meal) downloadRecipePdf(meal);
    })
  );
}

async function fetchMealById(id) {
  const res = await fetch(`https://www.themealdb.com/api/json/v1/1/lookup.php?i=${id}`);
  const data = await res.json();
  return data.meals?.[0];
}

async function downloadRecipePdf(meal) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const width = doc.internal.pageSize.getWidth();
  const height = doc.internal.pageSize.getHeight();
  const margin = 40;
  let y = 160;

  // 🍽️ HEADER BAR
  doc.setFillColor(255, 160, 122); // soft coral
  doc.rect(0, 0, width, 120, "F");
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(255, 255, 255);
  doc.text("🍳 My Recipe Book", margin, 70);

  // 🖼️ Dish image
  const imgData = await loadImageAsDataURL(meal.strMealThumb);
  doc.addImage(imgData, "JPEG", margin, y, 200, 200);
  y += 220;

  // 🧾 Recipe title
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.text(meal.strMeal, margin, y);
  y += 30;

  // Category & Cuisine
  doc.setFontSize(12);
  if (meal.strCategory) { doc.text(`Category: ${meal.strCategory}`, margin, y); y += 16; }
  if (meal.strArea) { doc.text(`Cuisine: ${meal.strArea}`, margin, y); y += 24; }

  // Ingredients section
  doc.setFont("Helvetica", "bold");
  doc.text("Ingredients:", margin, y);
  y += 18;
  doc.setFont("Helvetica", "normal");
  getIngredients(meal).forEach(i => {
    if (y > height - 80) { doc.addPage(); y = margin; }
    doc.text("• " + i, margin + 10, y);
    y += 16;
  });

  y += 16;
  doc.setFont("Helvetica", "bold");
  doc.text("Instructions:", margin, y);
  y += 18;
  doc.setFont("Helvetica", "normal");

  const lines = doc.splitTextToSize(meal.strInstructions || "", width - 2 * margin);
  lines.forEach(line => {
    if (y > height - 60) { doc.addPage(); y = margin; }
    doc.text(line, margin, y);
    y += 16;
  });

  // YouTube link
  if (meal.strYoutube) {
    y += 20;
    doc.setTextColor(0, 0, 255);
    doc.textWithLink("🎥 Watch tutorial", margin, y, { url: meal.strYoutube });
  }

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Generated by My Recipe Book ❤️", width - 220, height - 20);

  doc.save(`${sanitizeFileName(meal.strMeal)}.pdf`);
}

/* --------- Helpers --------- */
function sanitizeFileName(name="recipe") {
  return name.replace(/[^a-z0-9\s\-]/gi, "").trim().replace(/\s+/g, "-").slice(0, 120);
}

function loadImageAsDataURL(url) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/jpeg"));
    };
    img.onerror = reject;
    img.src = url;
  });
}
